# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('ocorrencia', 'Ocorrencia'), ('aviso', 'Aviso'), ('entrada', 'Entrada')], max_length=64, verbose_name='Tipo')),
                ('publico', models.BooleanField(default=False, verbose_name='Publico')),
                ('descricao', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descricao')),
                ('foto', models.CharField(blank=True, max_length=256, null=True, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=16, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portaria.Post')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('razoavel', 'Razoavel'), ('urgente', 'Urgente')], default='razoavel', max_length=256, verbose_name='Prioridade')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
            bases=('portaria.post',),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portaria.Post')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('status', models.CharField(choices=[('informada', 'Informada'), ('lida', 'Lida'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='informada', max_length=64, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
            bases=('portaria.post',),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portaria.Post')),
                ('status', models.CharField(choices=[('resolvido', 'Resolvido'), ('reaberta', 'Reaberta'), ('finalizada', 'Finalizada'), ('aberta', 'Aberta'), ('em_analise', 'Em Analise')], default='aberta', max_length=64, verbose_name='Status')),
                ('localizacao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Localizacao')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
            bases=('portaria.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='informante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='comum.Perfil'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='portaria.Ocorrencia'),
        ),
    ]
