# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0004_auto_20170926_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descricao')),
                ('informante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='comum.Perfil')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('resolvido', 'Resolvido'), ('reaberta', 'Reaberta'), ('finalizada', 'Finalizada'), ('aberta', 'Aberta'), ('em_analise', 'Em Analise')], default='aberta', max_length=64, verbose_name='Status')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descricao')),
                ('localizacao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Localizacao')),
                ('publico', models.BooleanField(default=False, verbose_name='Publico')),
                ('informante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='comum.Perfil')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.AddField(
            model_name='comentario',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='portaria.Ocorrencia'),
        ),
    ]
