# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(default='imgs/none/no_image.png', upload_to='imgs'),
        ),
    ]
