# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='status',
            field=models.CharField(choices=[('informada', 'Informada'), ('lida', 'Lida'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='informada', max_length=64, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
