# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='morador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='comum.Perfil'),
        ),
    ]
