# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_auto_20170930_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='portaria.Ocorrencia'),
        ),
    ]
