# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comum.Base')),
                ('cnpj', models.CharField(max_length=11, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=128, unique=True, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=128, verbose_name='Endereco')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
            bases=('comum.base',),
        ),
    ]
