# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='cnpj',
            field=models.CharField(max_length=11, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='unidadehabitacional',
            name='grupo_habitacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_habitacionais', to='comum.GrupoHabitacional'),
        ),
        migrations.AlterField(
            model_name='unidadehabitacional',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_habitacionais', to='comum.Perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='condominio',
            unique_together=set([('cnpj', 'nome')]),
        ),
    ]
