# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='portaria',
            field=models.BooleanField(default=False, verbose_name='Portaria'),
        ),
    ]
