# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoHabitacional',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comum.Base')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('quadra', 'Quadra'), ('bloco', 'Bloco'), ('torre', 'Torre')], max_length=64, verbose_name='Tipo')),
                ('tipo_unidade', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('chale', 'Chale')], max_length=64, verbose_name='Tipo unidade')),
                ('logradouro', models.CharField(blank=True, max_length=256, null=True, verbose_name='Logradouro')),
                ('cond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_habitacionais', to='comum.Condominio')),
            ],
            options={
                'verbose_name_plural': 'Grupos Habitacionais',
                'ordering': ('nome',),
                'verbose_name': 'Grupo Habitacional',
            },
            bases=('comum.base',),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comum.Base')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=16, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name_plural': 'Perfis',
                'verbose_name': 'Perfil',
            },
            bases=('comum.base',),
        ),
        migrations.CreateModel(
            name='UnidadeHabitacional',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comum.Base')),
                ('nome', models.CharField(max_length=16)),
                ('grupo_habitacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='comum.GrupoHabitacional')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='comum.Perfil')),
            ],
            options={
                'verbose_name_plural': 'Unidades habitacionais',
                'ordering': ('nome',),
                'verbose_name': 'Unidade habitacional',
            },
            bases=('comum.base',),
        ),
        migrations.AddField(
            model_name='perfil',
            name='unidade_habitacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='comum.UnidadeHabitacional'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='unidadehabitacional',
            unique_together=set([('nome', 'grupo_habitacional')]),
        ),
        migrations.AlterUniqueTogether(
            name='grupohabitacional',
            unique_together=set([('nome', 'cond')]),
        ),
    ]
