# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20170913_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='sindico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condominios', to='comum.Perfil'),
        ),
    ]
