# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_auto_20171110_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='sindico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condominio_administrado', to='comum.Perfil'),
        ),
    ]
