# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-26 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_auto_20180731_2019'),
        ('portaria', '0002_auto_20180821_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='morador',
        ),
        migrations.AddField(
            model_name='visitante',
            name='unidade_habitacional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='comum.UnidadeHabitacional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='status',
            field=models.CharField(choices=[('informada', 'Informada'), ('lida', 'Lida'), ('liberada', 'Liberada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='informada', max_length=64, verbose_name='Status'),
        ),
    ]
